"""add idempotency key

Revision ID: 27d6eaa1b56e
Revises: a6cc2dc342a4
Create Date: 2025-12-15 13:49:37.028432

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27d6eaa1b56e'
down_revision = 'a6cc2dc342a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('idempotency_key', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_payments_idempotency_key'), 'payments', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_idempotency_key'), table_name='payments')
    op.drop_column('payments', 'idempotency_key')
    # ### end Alembic commands ###
