"""change ids to bigint

Revision ID: d00a1d9c01f5
Revises: 27d6eaa1b56e
Create Date: 2025-12-24 16:37:29.707938

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd00a1d9c01f5'
down_revision = '27d6eaa1b56e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               postgresql_using="id::bigint")
    op.alter_column('payments', 'order_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               postgresql_using="order_id::bigint",)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'order_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               postgresql_using="order_id::integer",)
    op.alter_column('payments', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               postgresql_using="id::integer",)
    # ### end Alembic commands ###
